_format_version: '1.1'
services:
  # auth service without autorization
  - url: https://auth.jasanya.tech
    routes:
      - name: login
        paths: [ '/auth/login' ]
        strip_path: false
        methods: [ 'POST' ]
        protocols: [ 'http', 'https' ]
      - name: login-with-google
        paths: [ '/auth/login-google' ]
        strip_path: false
        methods: [ 'POST' ]
        protocols: [ 'http', 'https' ]
      - name: register
        paths: [ '/auth/register' ]
        strip_path: false
        methods: [ 'POST' ]
        protocols: [ 'http', 'https' ]
      - name: forgot-password
        paths: [ '/auth/forgot-password' ]
        strip_path: false
        methods: [ 'POST' ]
        protocols: [ 'http', 'https' ]
      - name: change-forgot-password
        paths: [ '/auth/forgot-password' ]
        strip_path: false
        methods: [ 'PUT' ]
        protocols: [ 'http', 'https' ]
      - name: generate-otp
        paths: [ '/auth/otp' ]
        strip_path: false
        methods: [ 'POST' ]
        protocols: [ 'http', 'https' ]
    plugins:
      - name: middleware
        config:
          auth: false
          account: false
          apiKeyAuth_header: ${{ secrets.API_KEY_AUTH }}
          key: ${{ secrets.API_KEY_AUTH }}

  # auth service with autorization
  - url: https://auth.jasanya.tech
    routes:
      # activasi-account
      - name: activasi-account
        paths: [ '/auth/activasi-account' ]
        strip_path: false
        methods: [ 'PUT' ]
        protocols: [ 'http', 'https' ]
      # change password
      - name: change-password
        paths: [ '/auth/change-password' ]
        strip_path: false
        methods: [ 'PUT' ]
        protocols: [ 'http', 'https' ]
      - name: change-username
        paths: [ '/auth/change-username' ]
        strip_path: false
        methods: [ 'PUT' ]
        protocols: [ 'http', 'https' ]
      # logout
      - name: logout
        paths: [ '/auth/logout' ]
        strip_path: false
        methods: [ 'POST' ]
        protocols: [ 'http', 'https' ]
    plugins:
      - name: middleware
        config:
          auth: true
          account: false
          apiKeyAuth_header: ${{ secrets.API_KEY_AUTH }}
          key: ${{ secrets.API_KEY_AUTH }}

# account service
  - url: https://account.dueit.my.id
    routes:
      - name: get-profile
        paths: [ '/account/profile' ]
        strip_path: false
        methods: [ 'GET' ]
        protocols: [ 'http', 'https' ]
      - name: update-account
        paths: [ '/account' ]
        strip_path: false
        methods: [ 'PUT' ]
        protocols: [ 'http', 'https' ]
      - name: create-profile-config
        paths: [ '/account/profile-config' ]
        strip_path: false
        methods: [ 'POST' ]
        protocols: [ 'http', 'https' ]
      - name: get-profile-config
        paths: [ '/account/profile-config/.+' ]
        strip_path: false
        methods: [ 'GET' ]
        protocols: [ 'http', 'https' ]
      - name: update-profile-config
        paths: [ '/account/profile-config/.+' ]
        strip_path: false
        methods: [ 'PUT' ]
        protocols: [ 'http', 'https' ]
    plugins:
      - name: middleware
        config:
          auth: true
          account: true
          apiKeyAuth_header: ${{ secrets.API_KEY_AUTH }}
          apiKeyAccount_header: "apikeyaccount"
          key: "apikeyaccount"

  #    finance service
  - url: https://finance.dueit.my.id
    routes:
      - name: payment
        paths: [ '/finance/payment' ]
        strip_path: false
        methods: [ 'GET' ]
      - name: create-payment
        paths: [ '/finance/payment' ]
        strip_path: false
        methods: [ 'POST' ]
      - name: PUT-payment
        paths: [ '/finance/payment/+.' ]
        strip_path: false
        methods: [ 'PUT' ]
      - name: delete-payment
        paths: [ '/finance/payment/+.' ]
        strip_path: false
        methods: [ 'DELETE' ]

      - name: get-by-periode-spending-type
        paths: [ '/finance/spending-type/+.' ]
        strip_path: false
        methods: [ 'GET' ]
      - name: get-all-spending-type
        paths: [ '/finance/spending-type' ]
        strip_path: false
        methods: [ 'GET' ]
      - name: detail-spending-type
        paths: [ '/finance/spending-type/detail/+.' ]
        strip_path: false
        methods: [ 'GET' ]
      - name: create-spending-type
        paths: [ '/finance/spending-type' ]
        strip_path: false
        methods: [ 'POST' ]
      - name: put-spending-type
        paths: [ '/finance/spending-type/+.' ]
        strip_path: false
        methods: [ 'PUT' ]
      - name: delete-spending-type
        paths: [ '/finance/spending-type/+.' ]
        strip_path: false
        methods: [ 'DELETE' ]

      - name: spending-history
        paths: [ '/finance/spending-history' ]
        strip_path: false
        methods: [ 'GET' ]
      - name: spending-history-detail
        paths: [ '/finance/spending-history/+.' ]
        strip_path: false
        methods: [ 'GET' ]
      - name: create-spending-history
        paths: [ '/finance/spending-history' ]
        strip_path: false
        methods: [ 'POST' ]
      - name: put-spending-history
        paths: [ '/finance/spending-history/+.' ]
        strip_path: false
        methods: [ 'PUT' ]
      - name: del-spending-history
        paths: [ '/finance/spending-history/+.' ]
        strip_path: false
        methods: [ 'DELETE' ]

      - name: get-all-income-type
        paths: [ '/finance/income-type' ]
        strip_path: false
        methods: [ 'GET' ]
      - name: detail-income-type
        paths: [ '/finance/income-type/detail/+.' ]
        strip_path: false
        methods: [ 'GET' ]
      - name: create-income-type
        paths: [ '/finance/income-type' ]
        strip_path: false
        methods: [ 'POST' ]
      - name: put-income-type
        paths: [ '/finance/income-type/+.' ]
        strip_path: false
        methods: [ 'PUT' ]
      - name: delete-income-type
        paths: [ '/finance/income-type/+.' ]
        strip_path: false
        methods: [ 'DELETE' ]

      - name: income-history
        paths: [ '/finance/income-history' ]
        strip_path: false
        methods: [ 'GET' ]
      - name: income-history-detail
        paths: [ '/finance/income-history/+.' ]
        strip_path: false
        methods: [ 'GET' ]
      - name: create-income-history
        paths: [ '/finance/income-history' ]
        strip_path: false
        methods: [ 'POST' ]
      - name: put-income-history
        paths: [ '/finance/income-history/+.' ]
        strip_path: false
        methods: [ 'PUT' ]
      - name: del-income-history
        paths: [ '/finance/income-history/+.' ]
        strip_path: false
        methods: [ 'DELETE' ]

      - name: balance
        paths: [ '/finance/balance' ]
        strip_path: false
        methods: [ 'GET' ]

    plugins:
      - name: middleware
        config:
          auth: true
          account: true
          apiKeyAuth_header: ${{ secrets.API_KEY_AUTH }}
          apiKeyAccount_header: "apikeyaccount"
          apiKeyFinance_header: "apikeyfinance"
          key: "apikeyfinance"
