_format_version: '1.1'
services:
  # auth service without autorization
  - url: https://auth.jasanya.tech
    routes:
      - name: login
        paths: [ '/auth/login' ]
        strip_path: false
        methods: [ 'POST' ]
        protocols: [ 'http', 'https' ]
      - name: login-with-google
        paths: [ '/auth/login-google' ]
        strip_path: false
        methods: [ 'POST' ]
        protocols: [ 'http', 'https' ]
      - name: register
        paths: [ '/auth/register' ]
        strip_path: false
        methods: [ 'POST' ]
        protocols: [ 'http', 'https' ]
      - name: forgot-password
        paths: [ '/auth/forgot-password' ]
        strip_path: false
        methods: [ 'POST' ]
        protocols: [ 'http', 'https' ]
      - name: change-forgot-password
        paths: [ '/auth/forgot-password' ]
        strip_path: false
        methods: [ 'PUT' ]
        protocols: [ 'http', 'https' ]
      - name: generate-otp
        paths: [ '/auth/otp' ]
        strip_path: false
        methods: [ 'POST' ]
        protocols: [ 'http', 'https' ]
    plugins:
      - name: cors
        config:
          origins:
            - "http://localhost:3000" # Ganti dengan domain yang diperbolehkan
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          headers:
            - Accept
            - Content-Type
            - Authorization
            - App-ID
            - User-ID
            - X-Key
            - X-Api-Key
            - Type
            # tambahkan header lain yang perlu Anda izinkan
          exposed_headers:
            - Authorization
            - App-ID
            - User-ID
            - Type
      - name: middleware
        config:
          auth: false
          account: false
          apiKeyAuth_header: REPLACE_WITH_API_KEY_AUTH
          key: REPLACE_WITH_API_KEY_AUTH

  # auth service with autorization
  - url: https://auth.jasanya.tech
    routes:
      # get-account
      - name: get-user
        paths: [ '/auth/user' ]
        strip_path: false
        methods: [ 'GET' ]
        protocols: [ 'http', 'https' ]
      # activasi-account
      - name: activasi-account
        paths: [ '/auth/activasi-account' ]
        strip_path: false
        methods: [ 'PUT' ]
        protocols: [ 'http', 'https' ]
      # change password
      - name: change-password
        paths: [ '/auth/change-password' ]
        strip_path: false
        methods: [ 'PUT' ]
        protocols: [ 'http', 'https' ]
      - name: change-username
        paths: [ '/auth/change-username' ]
        strip_path: false
        methods: [ 'PUT' ]
        protocols: [ 'http', 'https' ]
      # logout
      - name: logout
        paths: [ '/auth/logout' ]
        strip_path: false
        methods: [ 'POST' ]
        protocols: [ 'http', 'https' ]
    plugins:
      - name: cors
        config:
          origins:
            - "http://localhost:3000" # Ganti dengan domain yang diperbolehkan
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          headers:
            - Accept
            - Content-Type
            - Authorization
            - App-ID
            - User-ID
            - X-Key
            - X-Api-Key
            - Type
            # tambahkan header lain yang perlu Anda izinkan
          exposed_headers:
            - Authorization
            - App-ID
            - User-ID
            - Type
      - name: middleware
        config:
          auth: true
          account: false
          apiKeyAuth_header: REPLACE_WITH_API_KEY_AUTH
          key: REPLACE_WITH_API_KEY_AUTH

# account service
  - url: https://account.dueit.my.id
    routes:
      - name: get-profile
        paths: [ '/account/profile' ]
        strip_path: false
        methods: [ 'GET' ]
        protocols: [ 'http', 'https' ]
      - name: update-account
        paths: [ '/account' ]
        strip_path: false
        methods: [ 'PUT' ]
        protocols: [ 'http', 'https' ]
      - name: create-profile-config
        paths: [ '/account/profile-config' ]
        strip_path: false
        methods: [ 'POST' ]
        protocols: [ 'http', 'https' ]
      - name: get-profile-config
        paths: [ '/account/profile-config/.+' ]
        strip_path: false
        methods: [ 'GET' ]
        protocols: [ 'http', 'https' ]
      - name: get-all-notif
        paths: [ '/account/notif' ]
        strip_path: false
        methods: [ 'GET' ]
        protocols: [ 'http', 'https' ]
      - name: get-detail-notif
        paths: [ '/account/notif/.+' ]
        strip_path: false
        methods: [ 'GET' ]
        protocols: [ 'http', 'https' ]
      - name: put-detail-notif
        paths: [ '/account/notif/.+' ]
        strip_path: false
        methods: [ 'PUT' ]
        protocols: [ 'http', 'https' ]
      - name: delete-detail-notif
        paths: [ '/account/notif/.+' ]
        strip_path: false
        methods: [ 'DELETE' ]
        protocols: [ 'http', 'https' ]
      - name: delete-all-notif
        paths: [ '/account/notif' ]
        strip_path: false
        methods: [ 'DELETE' ]
        protocols: [ 'http', 'https' ]
    plugins:
      - name: cors
        config:
          origins:
            - "http://localhost:3000" # Ganti dengan domain yang diperbolehkan
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          headers:
            - Accept
            - Content-Type
            - Authorization
            - App-ID
            - User-ID
            - X-Key
            - X-Api-Key
            - Type
            # tambahkan header lain yang perlu Anda izinkan
          exposed_headers:
            - Authorization
            - App-ID
            - User-ID
            - Type
      - name: middleware
        config:
          auth: true
          account: true
          apiKeyAuth_header: REPLACE_WITH_API_KEY_AUTH
          apiKeyAccount_header: REPLACE_WITH_API_KEY_ACCOUNT
          key: REPLACE_WITH_API_KEY_ACCOUNT

  #    finance service
  - url: https://finance.dueit.my.id
    routes:
      - name: payment
        paths: [ '/finance/payment' ]
        strip_path: false
        methods: [ 'GET' ]
      - name: create-payment
        paths: [ '/finance/payment' ]
        strip_path: false
        methods: [ 'POST' ]
      - name: PUT-payment
        paths: [ '/finance/payment/+.' ]
        strip_path: false
        methods: [ 'PUT' ]
      - name: delete-payment
        paths: [ '/finance/payment/+.' ]
        strip_path: false
        methods: [ 'DELETE' ]

      - name: get-by-periode-spending-type
        paths: [ '/finance/spending-type/+.' ]
        strip_path: false
        methods: [ 'GET' ]
      - name: get-all-spending-type
        paths: [ '/finance/spending-type' ]
        strip_path: false
        methods: [ 'GET' ]
      - name: detail-spending-type
        paths: [ '/finance/spending-type/detail/+.' ]
        strip_path: false
        methods: [ 'GET' ]
      - name: create-spending-type
        paths: [ '/finance/spending-type' ]
        strip_path: false
        methods: [ 'POST' ]
      - name: put-spending-type
        paths: [ '/finance/spending-type/+.' ]
        strip_path: false
        methods: [ 'PUT' ]
      - name: delete-spending-type
        paths: [ '/finance/spending-type/+.' ]
        strip_path: false
        methods: [ 'DELETE' ]

      - name: spending-history
        paths: [ '/finance/spending-history' ]
        strip_path: false
        methods: [ 'GET' ]
      - name: spending-history-detail
        paths: [ '/finance/spending-history/+.' ]
        strip_path: false
        methods: [ 'GET' ]
      - name: create-spending-history
        paths: [ '/finance/spending-history' ]
        strip_path: false
        methods: [ 'POST' ]
      - name: put-spending-history
        paths: [ '/finance/spending-history/+.' ]
        strip_path: false
        methods: [ 'PUT' ]
      - name: del-spending-history
        paths: [ '/finance/spending-history/+.' ]
        strip_path: false
        methods: [ 'DELETE' ]

      - name: get-all-income-type
        paths: [ '/finance/income-type' ]
        strip_path: false
        methods: [ 'GET' ]
      - name: detail-income-type
        paths: [ '/finance/income-type/detail/+.' ]
        strip_path: false
        methods: [ 'GET' ]
      - name: create-income-type
        paths: [ '/finance/income-type' ]
        strip_path: false
        methods: [ 'POST' ]
      - name: put-income-type
        paths: [ '/finance/income-type/+.' ]
        strip_path: false
        methods: [ 'PUT' ]
      - name: delete-income-type
        paths: [ '/finance/income-type/+.' ]
        strip_path: false
        methods: [ 'DELETE' ]

      - name: income-history
        paths: [ '/finance/income-history' ]
        strip_path: false
        methods: [ 'GET' ]
      - name: income-history-detail
        paths: [ '/finance/income-history/+.' ]
        strip_path: false
        methods: [ 'GET' ]
      - name: create-income-history
        paths: [ '/finance/income-history' ]
        strip_path: false
        methods: [ 'POST' ]
      - name: put-income-history
        paths: [ '/finance/income-history/+.' ]
        strip_path: false
        methods: [ 'PUT' ]
      - name: del-income-history
        paths: [ '/finance/income-history/+.' ]
        strip_path: false
        methods: [ 'DELETE' ]

      - name: balance
        paths: [ '/finance/balance' ]
        strip_path: false
        methods: [ 'GET' ]

    plugins:
      - name: cors
        config:
          origins:
            - "http://localhost:3000" # Ganti dengan domain yang diperbolehkan
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          headers:
            - Accept
            - Content-Type
            - Authorization
            - App-ID
            - User-ID
            - X-Key
            - X-Api-Key
            - Type
            # tambahkan header lain yang perlu Anda izinkan
          exposed_headers:
            - Authorization
            - App-ID
            - User-ID
            - Type
      - name: middleware
        config:
          auth: true
          account: true
          apiKeyAuth_header: REPLACE_WITH_API_KEY_AUTH
          apiKeyAccount_header: REPLACE_WITH_API_KEY_ACCOUNT
          apiKeyFinance_header: REPLACE_WITH_API_KEY_FINANCE
          key: REPLACE_WITH_API_KEY_FINANCE

  - url: https://gql.dueit.my.id
    routes:
      - name: graphql
        paths: [ '/gql' ]
        strip_path: false
        methods: [ 'POST' ]
        protocols: [ 'http', 'https' ]
    plugins:
      - name: cors
        config:
          origins:
            - "http://localhost:3000" # Ganti dengan domain yang diperbolehkan
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          headers:
            - Accept
            - Content-Type
            - Authorization
            - App-ID
            - User-ID
            - X-Key
            - Type
            # tambahkaheader lain yang perlu Anda izinkan
          exposed_headers:
            - Authorization
            - App-ID
            - User-ID
            - Type
      - name: middleware
        config:
          auth: true
          account: true
          apiKeyAuth_header: REPLACE_WITH_API_KEY_AUTH
          apiKeyAccount_header: REPLACE_WITH_API_KEY_ACCOUNT
          key: REPLACE_WITH_API_KEY_PAGE
