_format_version: '1.1'
services:
  # not autorization
  - url: http://103.82.92.34:8080
    routes:
      - name: auth-service
        paths:
          [
            '/auth/login',
            '/auth/register',
            '/auth/refresh-token',
            '/auth/forgot-password',
            '/auth/change-forgot-password',
          ]
        strip_path: false
        methods: ['POST', 'POST', 'POST', 'POST', 'PUT']
        protocols: ['http', 'https']
    plugins:
      - name: key-checker
        config:
          apikey: secretkeyjasanyaauth

  # with autorization
  - url: http://103.82.92.34:8080
    routes:
      # get-otp
      - name: auth-service
        paths:
          [
            '/auth/get-otp',
            '/auth/logout',
            '/auth/activasi-account',
            '/auth/change-password',
          ]
        methods: ['POST', 'POST', 'PUT', 'PUT']
        strip_path: false
        protocols: ['http', 'https']
    plugins:
      - name: key-checker
        config:
          apikey: secretkeyjasanyaauth
      - name: custom-auth
        config:
          validation_endpoint: http://103.82.92.34:8080/auth/validate-token
          token_header: Authorization
          appid_header: App-Id
          userid_header: User-Id
          activasi_account: Activasi-Account

  - url: http://103.82.92.34:9090
    routes:
      - name: account-service
        paths: ['/profile/get-profile', '/profile/update-account']
        strip_path: false
        methods: ['GET', 'PUT']
        protocols: ['http', 'https']
    plugins:
      - name: key-checker
        config:
          apikey: secretkeyjasanyaauth
      - name: custom-auth
        config:
          validation_endpoint: http://103.82.92.34:8080/auth/validate-token
          token_header: Authorization
          appid_header: App-Id
          userid_header: User-Id
          activasi_account: Activasi-Account

  - url: http://103.82.92.34:9000
    routes:
      - name: minio
        paths: ['/files/user-images/public/.+']
        strip_path: false
        methods: ['GET']
        protocols: ['http', 'https']
