_format_version: '1.1'
services:
  # not autorization
  - url: https://auth.jasanya.tech
    routes:
      - name: login
        paths: ['/auth/login']
        strip_path: false
        methods: ['POST']
        protocols: ['http', 'https']
      - name: login-with-google
        paths: [ '/auth/login-google' ]
        strip_path: false
        methods: [ 'POST' ]
        protocols: [ 'http', 'https' ]
      - name: register
        paths: ['/auth/register']
        strip_path: false
        methods: ['POST']
        protocols: ['http', 'https']
      - name: forgot-password
        paths: ['/auth/forgot-password']
        strip_path: false
        methods: ['POST']
        protocols: ['http', 'https']
      - name: change-forgot-password
        paths: ['/auth/forgot-password']
        strip_path: false
        methods: ['PUT']
        protocols: ['http', 'https']
      - name: generate-otp
        paths: [ '/auth/otp' ]
        strip_path: false
        methods: [ 'POST' ]
        protocols: [ 'http', 'https' ]
#    plugins:
#      - name: key-checker
#        config:
#          apikey: secretkeyjasanyaauth

  # with autorization
  - url: https://auth.jasanya.tech
    routes:
      - name: get-otp
        paths: ['/auth/otp']
        strip_path: false
        methods: ['POST']
        protocols: ['http', 'https']
      # activasi-account
      - name: activasi-account
        paths: ['/auth/activasi-account']
        strip_path: false
        methods: ['PUT']
        protocols: ['http', 'https']
      # change password
      - name: change-password
        paths: ['/auth/change-password']
        strip_path: false
        methods: ['PUT']
        protocols: ['http', 'https']
      # logout
      - name: logout
        paths: ['/auth/logout']
        strip_path: false
        methods: ['POST']
        protocols: ['http', 'https']
    plugins:
#      - name: key-checker
#        config:
#          apikey: secretkeyjasanyaauth
      - name: custom-auth
        config:
          validation_endpoint: https://auth.jasanya.tech/auth/otorisasi
          token_header: Authorization
          appid_header: App-ID
          userid_header: User-ID

  - url: https://account.dueit.my.id
    routes:
      - name: get-profile
        paths: ['/account/profile']
        strip_path: false
        methods: ['GET']
        protocols: ['http', 'https']
      - name: update-account
        paths: ['/account/.+']
        strip_path: false
        methods: ['PUT']
        protocols: ['http', 'https']
      - name: create-profile-config
        paths: [ '/account/profile-config/.+' ]
        strip_path: false
        methods: [ 'POST' ]
        protocols: [ 'http', 'https' ]
      - name: get-profile-config
        paths: [ '/account/profile-config/.+' ]
        strip_path: false
        methods: [ 'GET' ]
        protocols: [ 'http', 'https' ]
      - name: update-profile-config
        paths: [ '/account/profile-config/.+' ]
        strip_path: false
        methods: [ 'PUT' ]
        protocols: [ 'http', 'https' ]
    plugins:
#      - name: key-checker
#        config:
#          apikey: secretkeyjasanyaauth
      - name: custom-auth
        config:
          validation_endpoint:  https://auth.jasanya.tech/auth/otorisasi
          token_header: Authorization
          appid_header: App-ID
          userid_header: User-ID
      - name: account-middleware
        config:
          validation_endpoint: https://account.dueit.my.id/account/otorisasi
          userid_header: User-ID
