version: '3'
services:
  kong:
    container_name: kong-dueit
    build: .
    ports:
      - '8000:8000'
    environment:
      KONG_DATABASE: 'off'
      KONG_GO_PLUGINS_DIR: /tmp/go-plugins
      KONG_DECLARATIVE_CONFIG: /tmp/config_production.yml
      # KONG_DECLARATIVE_CONFIG: /tmp/config.yml
      KONG_PLUGINS: custom-auth,key-checker
    networks:
      - dueit_network

networks:
  dueit_network:
    external: true