version: '3'
services:
  kong:
    container_name: kong-dueit
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_KEY_AUTH: your_auth_key
        API_KEY_ACCOUNT: your_account_key
        API_KEY_FINANCE: your_finance_key
    network_mode: host
#    ports:
#      - '8000:8000'
    environment:
      KONG_DATABASE: 'off'
      KONG_GO_PLUGINS_DIR: /tmp/go-plugins
      KONG_DECLARATIVE_CONFIG: /tmp/config_production.yml
      # KONG_DECLARATIVE_CONFIG: /tmp/config.yml
      KONG_PLUGINS: middleware