name: Go-apigateway

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup Go-apigateway
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: login to docker github registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          pull: true
          push: true
          tags: ghcr.io/dueit-jasanya-aturuang/kong-gateway:1.0
          build-args: |
            API_KEY_AUTH=${{ secrets.API_KEY_AUTH }}
            API_KEY_ACCOUNT=${{ secrets.API_KEY_ACCOUNT }}
            API_KEY_FINANCE=${{ secrets.API_KEY_FINANCE }}

      - name: deploy to hosting ssh main branch
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SERVER_SSHKEY }}
          script: ${{ secrets.SCRIPT }}
